version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - /home/stepium/matrix/tmp/logs/circus:/var/log/circus
    networks:
      - elk
    depends_on:
      - logstash

  metricbeat:
    build:
      context: metricbeat/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

networks:

  elk:
    driver: bridge
