metricbeat.modules:
  - module: system
    period: 1m
    metricsets:
      - cpu
      - filesystem
      - load
      - memory
      - network

  - module: postgres
      period: 1m
      metricsets:
        - database
        - bgwriter
        - activity
      hosts: ["postgres://127.0.0.1:5432"]

  - module: rabbitmq
    metricsets: ["node", "queue"]
    period: 1m
    hosts: ["localhost:5672"]
    username: guest

  - module: redis
    metricsets: ["info", "keyspace"]
    period: 1m
    hosts: ["127.0.0.1:6379"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "kibana:5601"
setup.dashboards.enabled: true
