metricbeat.modules:
  - module: system
    period: ${SYSTEM_PERIOD:1m}
    metricsets:
      - cpu
      - filesystem
      - load
      - memory
      - network
      - discio
    processes: ['.*']
    process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

  - module: postgresql
    period: ${POSTGRES_PERIOD:1m}
    metricsets:
      - database
      - bgwriter
      - activity
    hosts: ${POSTGRES_HOSTS:["postgres://127.0.0.1:5432"]}

  - module: rabbitmq
    metricsets: ${RABBITMQ_METRICSETS:["node", "queue"]}
    period: ${RABBITMQ_PERIOD:1m}
    hosts: ${RABBITMQ_HOSTS:["localhost:5672"]}
    username: guest

  - module: redis
    metricsets: ${REDIS_METRICSETS:["info", "keyspace"]}
    period: ${REDIS_PERIOD:1m}
    network: redis
    hosts: ${REDIS_HOSTS:["127.0.0.1:6379"]}

output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOSTS:["elasticsearch:9200"]}
setup.kibana:
  host: ${KIBANA_HOST:"127.0.0.1:5601"}
setup.dashboards.enabled: true
